# Small config to help refactoring to make the model completely YAML based
defaults:
  experiment:
    model_file: examples/output/<EXP>.mod
    hyp_file: examples/output/<EXP>.hyp
    out_file: examples/output/<EXP>.out
    err_file: examples/output/<EXP>.err
    run_for_epochs: 50
    eval_metrics: recall|nbest=1,recall|nbest=3,recall|nbest=5
  train:
    trainer: adam
    learning_rate: 0.01
    default_layer_dim: 64
    dropout: 0.0
    dev_metrics: recall|nbest=1,recall|nbest=3,recall|nbest=5
    training_corpus: !BilingualTrainingCorpus
      train_src: examples/data/head.ja
      train_trg: examples/data/head.smallids
      dev_src: examples/data/head.ja
      dev_trg: examples/data/head.smallids
    corpus_parser: !BilingualCorpusParser
      src_reader: !PlainTextReader {}
      trg_reader: !IDReader {}
    model: !DotProductRetriever
      src_embedder: !SimpleWordEmbedder
        vocab_size: 20000 # TODO: set this automatically
        emb_dim: 64
      src_encoder: !LSTMEncoder
        layers: 1
      trg_embedder: !SimpleWordEmbedder
        vocab_size: 20000 # TODO: set this automatically
        emb_dim: 64
      trg_encoder: !LSTMEncoder
        layers: 1
      database: !StandardRetrievalDatabase
        reader: !PlainTextReader {}
        database_file: examples/data/head.en
  decode:
    src_file: examples/data/head.ja
  evaluate:
    ref_file: examples/data/head.smallids

retriever:
